### ISSUE TITLE
Increase in modularity

### ISSUE THREAD

**Issue by danjee** [decebals/pippo#145]
I found that the current way of defining the application seems somehow monolithic:

```java
public class AjaxApplication extends Application {
     @Override
     protected void onInit() {
     ...
     }
}
...
public static void main(String[] args) {
   Pippo pippo = new Pippo(new AjaxApplication());
   pippo.start();
}
```
instead of

```java
@PippoExtension
public class AjaxApplication extends Application {
     @Override
     protected void onInit() {
     ...
     }
}
...
public static void main(String[] args) {
    Pippo pippo = new Pippo();
    pippo.start();
}
```
Wouldn't be better if we could have multiple classes that extends Application class and have them 
annotated with a marker so Pippo will read them on load? This way you gain more in modularity and let the developer needs split the code. 
You can even implement it with the pf4j framework, but this I think will increase the memory footprint of the core framework.
It will be like butter on toast for microservices applications! :boom:

**Comment by balamaci** [comment]
Hi,
I rather thought of Application more of a Singleton, I mean I don't imagine having multiple instances of Application inside the same war at least. And there is no need now to pass Application into Pippo with new Pippo(new AjaxApplication()). I personally am not a fan of too much magic and would rather have a necessary dependency stated upfront(in the Pippo constructor like it is now).

**Comment by danjee** [comment]
Indeed the current Application will not be singleton then and the class name will have to be refactor. I was thinking more on Spring Boot with its RestController services. 
Another downside for this change will be that the API will be broken. 
I don't think it will be magic but I think it will suit the needs for medium size apps not just smaller ones.

**Comment by gitblit** [comment]
Application is definitely a singleton in the current design.  While your proposal is interesting, I don't think we'd adopt it in Pippo as it adds complexity to something that is designed to be straight-forward. @decebals, of course, will have the final say.

Having said that, Pippo is purposefully built as a treasure trove of parts.  You can use Pippo as it's advertised & documented or you can remix it's components to build something that satisfies *your* need.  It's definitely possible to use most of Pippo as a first-class component within a larger, modular application and you can even have it do some magic. :stuck_out_tongue_winking_eye:

**Comment by decebals** [comment]
I think that we must have one `Application` instance in a project, this is the entry point in any application created with pippo.  In this class I do some configuration (`registerContentType`, `registerTemplateEngine`, `setRouter`, `createRequestResponseFactory`, ...) and I can add some routes (shortcut methods for `getRouter().addRoute()`).
The single part that it's candidate for modularity is the routes definition but you can achieve this using an `Initializer` in each module and in `init` you can do `application.GET(...)`. The problem is that we cannot guaranty now the order of the initializers but I think that we can add a `priority` integer variable but I don't know if it resolves the problem. Another way is via `pippo.ServiceLocator`.
I wish to see pippo in an application that uses an microservices architecture but I think that it's a bit too early :smile:

**Comment by danjee** [comment]
The `Initializer` solution is good enough for my scenario. Indeed a priority will be a nice addition but this is out of scope for this issue
