### ISSUE TITLE
Webjars relative path

### ISSUE THREAD

**Issue by danjee** [decebals/pippo#191]
I have an issue with using webjars that I couldn't find a solution for it. 
I've added the bootstrap webjar in the project and a reference to it. Inside the bootstrap.css
there is `@font-face` reference that loads the glyphicons fonts something like this:
 `src: url('../fonts/glyphicons-halflings-regular.eot');`
But when using the glyphicons class the path is not calculated correcty (e.g. the ../ is ignored) and the url 
is something like this:
`http://localhost:8080/webjars/bootstrap/css/fonts/glyphicons-halflings-regular.woff2 ` 

When using CDN everything seems OK.
An example is here:

https://github.com/danjee/sqlxplr/blob/master/src/main/resources/public/index.html

**Comment by decebals** [comment]
I clone your project locally and I made some tests.
I made also a little code review :smile: It's shortly to use lambdas if you use java 1.8
```java
GET("/", routeContext -> {
    Response response = routeContext.getResponse();
    response.html().resource(getClass().getResourceAsStream("/public/index.html"));
});

GET("/jdbc/connections", routeContext -> routeContext.json().send(getJsonConnections()));
```

I used `response.html().resource(getClass().getResourceAsStream("/public/index.html"))` to serve static file or `routeContext.redirect("/app/index.html");`, you cannot render templates because you don't have a template engine in your application.

In conclusion, I don't know if this bug is related to pippo (our webjars implemntation). Maybe @gitblit can say more.
As a workaround you maybe can add and use webjar for font-awesome

**Comment by danjee** [comment]
I've used the same webjar from wicket-bootstrap and it worked giving me the right path to the fonts.  I'm in the phase of learning java 8. I will review my code and make it as functional as I can. For the moment I didn't want a template engine, just plain html and css

**Comment by decebals** [comment]
I think that I found (visual) the bug in `ResourceHandler.getNormalizedPath()`. I will make some tests to confirm that it's what we need.

**Comment by decebals** [comment]
My assumption from my last comment is wrong. I don't know who resolves the `src: url(../fonts/glyphicons-halflings-regular.woff2` line from `bootstrap.css` but in the chrome console the request made is `http://localhost:8080/webjars/bootstrap/3.3.5/css/fonts/glyphicons-halflings-regular.woff2` and so appears in PippoFilter.

**Comment by danjee** [comment]
Yes, I saw the extra `css` in the path myself also in Firefox console. I don't really know how CSS calculates paths and why the `../` is ignored

**Comment by gitblit** [comment]
I just modified the CrudNg app to use a Glyphicon.  The font file is loaded fine from Chrome and FF.

The* browser* resolves the "../" relative to the path from which the *current* css resource is loaded.  I am seeing requests to `http://localhost:8080/webjars/bootstrap//fonts/glyphicons-halflings-regular.woff` which matches my expectation since my header link is `${webjarsAt('bootstrap/css/bootstrap.min.css')}`. The `fonts` dir is a sibling to `css` so I would expect `../fonts/fontfile.woff`.

**Comment by decebals** [comment]
Maybe the difference is that @danjee uses `<link href="/webjars/bootstrap/3.3.5/css/bootstrap.min.css/" rel="stylesheet">` in a static html page (without a template engine) and you use `${webjarsAt('bootstrap/css/bootstrap.min.css')}`.

**Comment by gitblit** [comment]
Hmm.  Good catch.  Our webjars support was written to support our template engines. I never considered to use it outside that scope - but I suppose if you were writing a frontend as a separate project that could make sense - although you lose the version aliasing we just introduced.  That must be why @danjee requested `/jquery/current` syntax.  We may still be able to support that particular use-case.

But on this issue.... the trailing `/` on the manually defined CSS `<link>`  may be the source of the trouble.

**Comment by danjee** [comment]
@gitblit You right, by removing the trailing `/` in the link `<link>` declaration the  404 error disappeared.
