### ISSUE TITLE
Freemarker template reloading not working in dev mode

### ISSUE THREAD

**Issue by aymer** [decebals/pippo#269]
Hi,

Not sure if I'm doing something wrong, but I'v set the pippo.mode to 'dev' and I'd expect templates to be autoreloaded on edit (as per doc) but doesn't seems to be, I've to restart server to see it reflected.

2016-04-30 11:38:30.983 [XNIO-1 task-1] INFO  ro.pippo.core.PippoFilter - Pippo started (DEV)

I could see the same behavior with https://github.com/decebals/pippo-demo/tree/master/pippo-demo-template.

**Comment by decebals** [comment]
When you start Pippo in `DEV` mode, the templates cache is disabled. 
I encountered the same issue in my first projects because in IDEA IntelliJ (my IDE), on `Ctrl-S` the IntelliJ only saves the content in the file but this is not enough. In my case `Ctrl-Shift-S` (compile the current file) resolves the problem (I think that on compile the IntelliJ updates the classes folder). You can map the Ctrl-Shift-S to Ctrl-S for a easy use.

**Comment by aymer** [comment]
Yes, thanks for the hints, it did the trick!
