### ISSUE TITLE
techempower benchmark ?

### ISSUE THREAD

**Issue by robertoestivill** [decebals/pippo#277]
I think that it would be great to have pippo in the Techempower benchmark.

https://www.techempower.com/benchmarks

It will not only help to get pippo known (a lot of devs use that site to choose technologies/frameworks), but also to be compared with lot's of other technologies.

What do you think?

**Comment by decebals** [comment]
I think that it's a good idea. I am curios to see how Pippo compares with other technologies. For me the big problem is the time. For example, I opened a new branch for each #275, #254 and #237 and I don't find time to finish them.
I will take a look to see how much effort is for to add Pippo to techempower benchmark.

**Comment by robertoestivill** [comment]
Thanks for the quick response :)
I understand. Time is a precious good nowadays.

Here are the guidelines on how to create the tests: https://www.techempower.com/benchmarks/#section=code

I will take a look and see if I find the time to help out with this. Some of the tests look pretty trivial, but I don't know much about pippo.

**Comment by robertoestivill** [comment]
Hi @decebals 
I had some time lately and decided to give this a go. 
I have implemented all 6 tests for MySQL and PostgreSQL using Undertow as the server.

I have a fork of the benchmark repo here (branch pippo, directory frameworks/Java/pippo-undertow):
https://github.com/robertoestivill/FrameworkBenchmarks/

To Do

- Add test config, setup, etc. 

Nice to have

- Implement Dao.java for Mongo db.
- Investigate better connection db pool size parameters
- Implement tests for Jetty and Tomcat.

Regarding the last point:
Is there any way to configure the server implementation at runtime? Or we have to create new maven modules to include the different server dependencies? Ideally we could just have a single project with different parameters to use an specific version.

Im pretty new to pippo, so it would be great to have some feedback before submitting the PR.

Thanks!

**Comment by decebals** [comment]
I will take a look. Thanks.

**Comment by robertoestivill** [comment]
Actually, I had some time yesterday, the mongo dao has been implemented too.
Cheers

**Comment by robertoestivill** [comment]
Everything is on the pippo branch by the way.
Also, Im failing to run the integration test against the fat-jar (but works fine in intellij) with this exception

https://gist.github.com/robertoestivill/2694652187c846fb041409c14799d80e

Any idea?

**Comment by decebals** [comment]
I finished the review of your code. The code looks good (clear and fast).
For this kind of benchmark I see three zones where you can gain or loose the battle:
- database integration
- server (servlet container: undertow, jetty, tomcat, ...)
- web framework

So, in theory you can have a good web framework but with a bad database integration and/or server you loose the battle.

Your implementation is very good and your choice for undertow is an excellent idea.  

> Also, Im failing to run the integration test against the fat-jar (but works fine in intellij) with this exception
https://gist.github.com/robertoestivill/2694652187c846fb041409c14799d80e

I didn't know that fat-jar works with Pippo. I used the deployment method described in [documentation](http://www.pippo.ro/doc/deployment.html). Maybe you must try to use another template engine (Pebble is my favorite because is fast and it has a nice syntax) and to see the result.

Thanks for your work. I appreciate very much your effort.

**Comment by gitblit** [comment]
@robertoestivill Thanks for taking this on.  I am interested to see where we fall whenever this gets merged and they re-run the tests.  At my employer we are seriously considering ASP.NET Core for a new project so I am doubly interested to see how we fare against that (I believe MS implemented the code for techempower so ASP.NET Core should be on the next run of tests too).

As for packaging/deployment.  Decebal already wrote about the manifest-based deploy.  I have used [Stork](https://github.com/fizzed/stork) with success (albeit it is a more complex solution than the manifest approach).  I have also had success with [Capsule](http://www.capsule.io/), which is a similar to your fat jar approach.

**Comment by robertoestivill** [comment]
Thank you both for your feedback.

I will be trying the assembly packaging option during this weekend. I really want to have that integration test running without errors.

@decebals  As for the container, I would love to have the test running on all supported servers. Is there any way to configure the server implementation at runtime? 

If not, I was thinking about having a base module with the common code, and having different artifacts that will only change the server implementation. Something like the following

- benchmark-base (common code, server agnostic) 
- benchmark-undertow (depends on benchmark-base and adds pippo-undertow)
- benchmark-tomcat (depends on benchmark-base and adds pippo-tomcat)
- benchmark-jetty (depends on benchmark-base and adds pippo-jetty)

Thoughts?

**Comment by gitblit** [comment]
You could subclass Pippo and override [`getServer()`](https://github.com/decebals/pippo/blob/master/pippo-core/src/main/java/ro/pippo/core/Pippo.java#L57-L71).

You would replace the `ServiceLocator` call with something that instantiates your desired server implementation. e.g. `UndertowServer`, `JettyServer`, etc.

**Comment by decebals** [comment]
Added method `setServer(WebServer server)` in the `Pippo` class.

**Comment by etemelkuran** [comment]
Why you need seperate benchmark? you can check servlet+jetty or servlet+undertow and assume.

**Comment by robertoestivill** [comment]
@etemelkuran because if you select any of the alternatives you mentioned, you will not be including pippo's overhead as a framework into account.

**Comment by etemelkuran** [comment]
sure you're right but it will not cost much.
i still can't understand java, golang is much easier :dancers: .
https://www.techempower.com/benchmarks/#section=data-r12&hw=peak&test=plaintext

**Comment by robertoestivill** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/pull/2244

**Comment by decebals** [comment]
@robertoestivill Very good work!
Your code is clear and have a simple structure. Maybe we can improve a little bit the performance changing some settings in the web server or the template engine, adding some index in the database, but it's another story.
Thanks for your contribution!

**Comment by decebals** [comment]
@robertoestivill  I think that the link to Pippo is wrong in https://github.com/TechEmpower/FrameworkBenchmarks/pull/2244#issue-173522204

**Comment by robertoestivill** [comment]
@decebals absolutely. The main reason for passing in the server, was to be able to fine tune each specific implementation. I do not know much about that, but I can do some research in a few days.

Regarding the database, I don't think we can do much because Techempower is the one that supplies them. We don't have control over it, we just connect to it under a fixed set of parameters and schemas. I added some helper files to be able to run it locally in an easier way (docker + main method or fatjar)

Techempower provides a vagrant+virtualbox environment to run all the tests, but it's pretty bad. It takes forever and you have to hack it a little bit as it always clones the official repo, instead of taking a parameter or a config where you can set it to clone your fork.

Indeed the link was wrong, just fixed it.

**Comment by decebals** [comment]
A little bit out of topic, in your code I see [BenchmarkTests](https://github.com/robertoestivill/FrameworkBenchmarks/blob/52ba4059e32397eee8ca81d1fa1f65cc64bcb8a9/frameworks/Java/pippo/src/test/java/ro/pippo/benchmark/BenchmarkTests.java) that uses [OkHttp](http://square.github.io/okhttp/) as HTTP client. I didn't know about this library.
Pippo comes with some unit tests in [RequestTest](https://github.com/decebals/pippo/blob/master/pippo-core/src/test/java/ro/pippo/core/RequestTest.java) class where I mocked a `HttpServletRequest` but are some situation (an example is #306) when I need some functional tests. For functional tests I used with success [PippoTest](https://github.com/decebals/pippo/blob/master/pippo-test/src/main/java/ro/pippo/test/PippoTest.java) class that is a tiny wrapper over [RestAssured](https://github.com/rest-assured/rest-assured) Java DSL for easy testing of REST services. 
My questions:
- What is the difference between OkHttp and Apache HttpClient? 
- Do you prefer to use in your tests an http client (ok or apache) instead of `PippoTester`?  

By the way, will be nice when someone reports an issue similar with #306, to receive from the reporter  a functional test that replicate the problem and eventually to add that test in the test suites.

**Comment by robertoestivill** [comment]
OkHttp is a very well known (almost de-facto I would say) http client for Android for various reasons.
1. Early versions of Android had a lot of issues with it's implementation/upgrades of apache httpclient and java urlconnection.
2. Plays very well with [Retrofit](http://square.github.io/retrofit/).
3. It has a very nice API (even without retrofit)
4. First http client available for android with Spdy support
5. Relatively fast iterations and android related fixes.
6. Very few dependencies (which is very important on android) 
7. It uses [Okio](http://github.com/square/okio) for fast IO.

The reason why I used this library was because during development of the benchmark I needed a functional test to check that every refactor I made didn't break anything. Since I'm coming from the Android world, it was super easy for me to use OkHttp. I have not been following apache httpclient development.

I was not aware of PippoTester to be completely honest with you. I will take a look whenever I have time and maybe change the test to use it.
