### ISSUE TITLE
Persistent sessions support

### ISSUE THREAD

**Issue by vemacs** [decebals/pippo#319]
Persisting sessions is important for smoothing out application restarts (so CSRF tokens are retained, etc...)

[Jetty does support persisting sessions to disk](https://www.eclipse.org/jetty/documentation/9.3.x/using-persistent-sessions.html), but it requires all the tedious XML configuration and things associated with it, and the current session persistence implementations in Pippo are all Redis-backed and the like. An API where you can simply provide a path for the saved session file would be greatly appreciated.

**Comment by decebals** [comment]
> the current session persistence implementations in Pippo are all Redis-backed and the like

I don't understand the above sentence, please explain.

We save the `SessionData` stored in different storage (http://www.pippo.ro/doc/session.html). The problem is that the servlet container (Jetty, Tomcat, ...) must somehow on start to load all these `SessionData`. Pippo is very flexible and modular so we can customize very well each instance of Servlet container, a method is described in https://github.com/decebals/pippo/issues/313#issuecomment-247655940. I think that it's a correspondence in Java code for that Jetty's XML configuration. If I have a little free time I will investigate the modifications for Jetty (to achieve persistent sessions).

**Comment by vemacs** [comment]
Oh wow, didn't know that was directly possible. Thanks.
