### ISSUE TITLE
Wrong content-type in the response

### ISSUE THREAD

**Issue by munendrasn** [decebals/pippo#335]
```java
routeContext.setHeader("content-type", "application/xml") // this wont work
routeContext.getResponse().getHttpServletResponse().getWriter()
//write something
```
In this case, response content-type would be `text/html`. It is because, in `Response` class, `getHeaderMap()` stores all added headers and adds to `httpServletResponse` only when `finalizeResponse()` is called.
In the above case, `finalizeResponse` method is never called.

Possible solutions:

- expose a `getWriter()` method in `Response` class to fetch `writer` 
```java
getWriter() { 
try{ 
htttpServeltResponse.getWriter()
} catch (IOException e) {
 // throw pippo runtime
}
}
```
-  instead of adding new header to `getHeaderMap` add directly to `httpServletResponse`

Let me know if there are any other better ways. Please let me know, If any of these approach is good  I will raise a PR for the same

**Comment by decebals** [comment]
For writing an xml as response, I use 
```java
// send xml as response
GET("/xml", routeContext -> {
    Contact contact = createContact();
    routeContext.xml().send(contact);
    // or 
   // routeConstext.xml().send(xmlAsString);
});
```

Your approach is too low in my opinion.

Sure, it's a bug but this situation appears because you want to bypass the `Response` wrapper and to use directly the raw, `HttpServletResponse`.

Probably the quick fix is to add a new method `getWritter()` in `Response` with an implementation similar with `getOutputStream()` (call on `checkCommitted`, `finalizeResponse`).

A more safe (and complex) approach is probably to use a `HttpServletResponseWrapper` in `Response`, class that fires automatically the `finalizeResponse` method and also call `checkCommit` method. I will think a solution based on this idea but probably not so fast.

**Comment by munendrasn** [comment]
@decebals, I also agree with you. Better approach would be using `xml()` or any other content method but in some-cases , setting content-type is required using `setHeader()`.
I think exposing `HttpServletResponseWrapper ` would be better approach. Also, to avoid bypassing   `Response`, `get HttpServletResponseWrapper()` could be removed.
For now, [fast fix] would be too add `getWriter` method. If you agree with this, i will send a PR for same or we could wait for others opinion also

**Comment by decebals** [comment]
You can send a PR with `getWriter` method. Please check first that this method resolve your problem. Thanks!

**Comment by munendrasn** [comment]
I tested it in application after adding `getWriter`, it is working. Raised PR #336
