### ISSUE TITLE
RxJava

### ISSUE THREAD

**Issue by danjee** [decebals/pippo#351]
Hello,
What do you think about adding RxJava into the scene?

**Comment by decebals** [comment]
How do you see this marriage from integration point of view? 
What value brings RxJava for Pippo?

**Comment by balamaci** [comment]
RxJava / Spring Reactor biggest value is when you have many asynchronous operation happening an you need a clear flow on how to handle the response. This ties to calling many microservices endpoints to service a user's request. 
Short paranthesis RxJava is active in the Android land(with gui callbacks being the async ops) while for enterprise java developers I think Spring Reactor will be a bigger deal as Spring seems to have invested more time(and money as they hired developers who work full time on Spring Reactor). Spring Reactor (being a major feature they have planned for Spring5) to offer a reactive alternative to spring-mvc and other spring projects. 
Btw RxJava and Spring Reactor are very very similar in the API and how they work. 
But notice that to get the full value of a reactive service they do deploy the spring-web-reactive services into RxNetty or ReactorNetty servers. 
Still this is not a show stopper for pippo, because we can use RxJava with no problem to call backend  microservices or reactive repositories. In the end to switch back from reactive to a blocking world with the .toBlocking() operator and serve the web page. But being Servlet based(one-thread-per-reques), with pippo we don't have the benefit of non-blocking webframeworks(fewer resources for a large number of users). 

Ratpack framework is also reactive web framework designed from the start and doesn't follow the Servlet specs and only runs on Netty.

**Comment by danjee** [comment]
Also with jdk 9 they try to standardize this with the Flow API. Like Șerban said Spring 5 will add a bunch of new capabilities supporting this:
[Functional web framework](https://spring.io/blog/2016/09/22/new-in-spring-5-functional-web-framework)
