### ISSUE TITLE
Is Pippo production ready

### ISSUE THREAD

**Issue by jaytheking** [decebals/pippo#364]
Im looking at coverage for pip and its currently at 18% give or take. Im exploring a couple of micro frameworks to split our current monolith up. Ive looked at SparkJava, Jooby and now pippo is next on my list.

The other question is it possible to use gradle for building.

**Comment by decebals** [comment]
@jaytheking 

> Im looking at coverage for pip and its currently at 18% give or take. Im exploring a couple of micro frameworks to split our current monolith up. Ive looked at SparkJava, Jooby and now pippo is next on my list.

Yes, you are right. The coverage is a problem and this because they are many modules (see pippo-sesion-parent for example) that are less or more used. The last two releases come with support for Hot reloading and Web socket and for next releases I don't have in pipe a new major feature and probably it's a good time to work on coverage. On the other side, if you take a look on the issues list you will see that they are only questions and enhancements. The library is production ready.

> The other question is it possible to use gradle for building.

The build process with Maven is trivial, nothing special. I don't use/know Gradle but if you come with a contribution I am ready to add it.

**Comment by jaytheking** [comment]
> The build process with Maven is trivial, nothing special. I don't use/know Gradle but if you come with a contribution I am ready to add it.

I only know the basics of gradle but prefer it over maven as i feel maven is heavy. So basically if i can just import the dependencies like i would in maven and dont have to worry about a maven specific build system then i think it should be simple to make one for the project.

**Comment by decebals** [comment]
I think that the build system should be transparent for you (the user of library). When I add/fix something I publish a new SNAPSHOT version. In this mode you are up to date and you are not forced to build Pippo  on your machine or to wait the release version.

**Comment by jaytheking** [comment]
@decebals Yeah agreed. Im just looking at the Maven build and its straight forward enough to do a Gradle script. Appreciate you getting back to me as fast as you did.
