### ISSUE TITLE
Settings for routes ending with slash / to be the same as the routes wihtout

### ISSUE THREAD

**Issue by 2beers** [decebals/pippo#366]
Is there a setting that treats a path like this `localhost/test` and `localhost/test/` the same way?

So far I'm doing this
`GET("/test", routeContext -> {});` and `GET("/test/", routeContext -> {});` 

Thanks

**Comment by decebals** [comment]
`GET("/test", routeContext -> {});` is similar with `GET("/test/", routeContext -> {});`

**Comment by 2beers** [comment]
Just tested again. For me they are treated as 2 different rules
If I define this route
```
GET("/test", routeContext -> {
	System.out.println("/test");
});
```
 and navigate to this `localhost/test/` nothing happens. It works only if I navigate to `localhost/test` without ending slash.

To make it work I need to add a secondary rule:
```
GET("/test/", routeContext -> {
	System.out.println("/test/");
});
```

Am I doing something wrong?

**Comment by decebals** [comment]
Sorry for delay. I was in a mini vacation. 
My idea is to preserve the actual behavior (`/users` and `/users/` are different) and to create a new `TrailingSlashHandler` class that should add or remove (a flag parameter in constructor) the slash character to or from the end of the request url. You can use this handler as a before filter (in front of all routes).
What you think?

**Comment by 2beers** [comment]
I also think this is a good idea, because sometimes I need those to be separate routes, however most of the time I don't and is annoying to define 2 routes that do the same thing.  
Is the TrailingSlashHandler already implemented or it's something that's coming ?

**Comment by decebals** [comment]
I create a new remote branch (https://github.com/decebals/pippo/tree/trailing_slash) with a possible implementation for `TrailingSlashHandler`. See https://github.com/decebals/pippo/pull/370 for details.

**Comment by decebals** [comment]
Another option tested by me was to adjust the request path (add or remove trailing slash) and after this to forward the request with the new path to the next route from chain. The problem here was that the `Router.findRoutes()` was already called and the routes are retrieved based on the original request path. In conclusion is to late to modify the request path in a before filter route. We need a mechanism to modify the initial `Request` (and probably `Response`) object(s) before to call `Router.findRoutes()`
In this situation, the only solution available write now (without to introduce a new concept) is to add a custom `RoutePreDispatchListener` via `Application.getRoutePreDispatchListeners()` method, to modify the request path in `void onPreDispatch(Request request, Response response)`.

I wrote all this to keep a track. More about this subject in "Pippo in Action" book :smile:

**Comment by munendrasn** [comment]
@decebals,
Could we expose additional methods in `Routing`(one method for each HTTP method), which takes one optional boolean parameter( to decide whether to add one extra route for given uriPattern)

For example, `GET(String uriPattern, RouteHandler routeHandler, boolean addTrailingRoute)`
Based on the last parameter, we could decide to add one more route.

Sample implementation:
```java
default void GET(String uriPattern, RouteHandler routeHandler, boolean addTrailingRoute) {
        if (routeHandler instanceof ResourceHandler) {
            throw new PippoRuntimeException("Please use 'addResourceRoute()'");
        }

        Route route = Route.GET(uriPattern, routeHandler);
        addRoute(route);
       if (addTrailingRoute)
          // handle case to add `/` to uriPattern and also add new `Route`
    }
```

### Advantage:
* decide to handle trailing on API level (in case of TrailingSlashHandler, handling of trailing slash on API level no possible). With these `/users`, `/users/` could mean same, at the same time `/id`, `/id/` would be made to treat as different

### Disadvantage:
* methods in `Routing` related to HTTP method might return two routes, hence return type of method would change (either to `void` or `List<Route>`). I haven't found any use case to return `Route` from the method(maybe I'm wrong) but this change would be incompatible with older versions of Pippo. Is there a use-case to return created `Route`

**Comment by decebals** [comment]
@munendrasn It's smell me like a black magic. I try to add a route but the final is that two routes are added. I prefer to add explicitly the `TrailingSlashHandler`. It's a little bit verbose (an extra line) but the result is very clear.

> decide to handle trailing on API level (in case of TrailingSlashHandler, handling of trailing slash on API level no possible). With these /users, /users/ could mean same, at the same time /id, /id/ would be made to treat as different

You can add `TrailingSlashHandler` only on `/users` if you want (using `GET("/users", new TrailingSlashHandler(false)`)

**Comment by decebals** [comment]
@kashike 
```java
@POST("/foo/bar/")
public void foo() {
    // ...
}
```
```
00:20:41] [XNIO-1 task-1/DEBUG] [DefaultRouter]: Add route for POST '/foo/bar'
[00:18:46] [XNIO-1 task-1/DEBUG] [PippoFilter]: Request POST '/foo/bar/'
```

It's smell like a bug because you register a POST route with path `/foo/bar/` and the request is for `/foo/bar/` also.
`TrailingSlashHandler` is useful when you register a (GET) route with path `/foo/bar/` and the request is for `/foo/bar` (without `/` to the end) and you want to use the same handler for both.

@mhagnumdw 
It's interesting to see if a route's urlPattern based on regex (Pippo supports regex in urlPattern when you register a route) is not a more natural solution instead of `TrailingSlashHandler`.

**Comment by kashike** [comment]
I assumed you remove trailing slashes from all registered routes intentionally - if this is not the case then it is, indeed, a bug. Should I open a separate issue?

**Comment by decebals** [comment]
> We need a mechanism to modify the initial Request (and probably Response) object(s) before to call Router.findRoutes()

`RouteTransformer` mechanism is already implemented.
