### ISSUE TITLE
Decide if Pippo apps can be distributed as a WAR

### ISSUE THREAD

**Issue by gitblit** [decebals/pippo#50]
I'm on the fence on this issue.  Supporting inconsistencies with other containers is always a nuisance.  Having a single deployable product that behaves in production exactly as in development is pretty handy.

The biggest thing we lose is container authentication - but I have always implemented my own anyway.  

Either way we need to decide if Pippo apps require their own dedicated container or if they can be distributed as WARs.

**Comment by decebals** [comment]
I made a test to see if I can run pippo-demo as a WAR using an external container (jetty). I can say that everything is OK.

Steps
- uncomment some lines in `pippo-demo/pom.xml`
```xml
<!--
<exclusions>
    <exclusion>
        <groupId>ro.fortsoft.pippo</groupId>
        <artifactId>pippo-jetty</artifactId>
    </exclusion>
 </exclusions>
-->
```
because I don't want pippo-jetty module in my war
```xml
<!--
<plugin>
	<groupId>org.eclipse.jetty</groupId>
	<artifactId>jetty-maven-plugin</artifactId>
	<version>9.2.0.v20140526</version>
	<configuration>
		<scanIntervalSeconds>10</scanIntervalSeconds>
		<stopKey>foo</stopKey>
		<stopPort>9999</stopPort>
		<webApp>
			<contextPath>/</contextPath>
		</webApp>
	</configuration>
</plugin>

<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-war-plugin</artifactId>
	<version>2.5</version>
</plugin>
-->
```
because I want to use `jetty-maven-plugin` to start an external jetty container
- uncomment some lines in `web.xml` from pippo-demo
```xml
<!--
<filter>
	<filter-name>pippo</filter-name>
	<filter-class>ro.fortsoft.pippo.core.PippoFilter</filter-class>
	<init-param>
		<param-name>applicationClassName</param-name>
		<param-value>ro.fortsoft.pippo.demo.SimpleApplication</param-value>
	</init-param>
</filter>

<filter-mapping>
	<filter-name>pippo</filter-name>
	<url-pattern>/*</url-pattern>
</filter-mapping>
-->
``` 
if you want to run other demo application then change `ro.fortsoft.pippo.demo.SimpleApplication` with something else
- run some commands from command line
```
mvn clean install
cd pippo-demo
mvn war:war
mvn jetty:run-war
```
now the application is available at `localhost:8080`

**Comment by gitblit** [comment]
Great.  Decision made.
