### ISSUE TITLE
Rethink Response.commit()

### ISSUE THREAD

**Issue by gitblit** [decebals/pippo#66]
In `Response.commit()` we are flushing the buffer which forces *chunked transfer encoding* and finalizes the servlet response.

It feels wrong that we are doing this.  I can't point to documentation that says this is a problem, but I can look at other frameworks and see they do not flush anything and thus do not force chunked encoding.

I think we need to consider some alternative (internal) mechanism for finalizing a response.

**Comment by gitblit** [comment]
Hmm.  Maybe this is not a problem.
http://zoompf.com/blog/2012/05/too-chunky

I am still unsure about committing mid-chain.

**Comment by decebals** [comment]
Initial `Response.commit()` was called in `send`, `file`, `resource`. Means that the response is sent and I cannot do something useful in the next route handlers from chain (if in my route handler that committed the response I call `chain.next` to the end of handle method).
I want to talk more about filters.
Now a `Filter` is a RouteHandler from a `RouteHandlerChain`.  We can split the filters in two types: 
- before
- after 

A `before` filter can set some parameters on response (I don't know if it's ok to commit the response in this stage). An example of the before filter is a possible `AuthenticationFilter`.
Another example of the before filter is a possible `BeginTransactionFilter` (open a connection to a database and start a transaction on each request).
An `after` filter also can set something  on Response but it's a non sens because the response was committed. 
Another example of the before filter is a possible `EndTransactionFilter` (commit/rollback the transaction started in BeginTransactionFilter).
Anytime in a RouteHandler I know if makes sense to call `chain.next` (to call the next handler in chain) or to break the chain (simple don't call chain.next).
I know that some (java) web frameworks with the same profile as pippo (SparkJava, Ninja) use a wrapper object (Object in spark and Result in ninja) and at the end of request handling, in the filter (in case of spark because ninja it's not servlet base), the framework try to send the content/body converting that wrapper object in string. I prefer to expose the Response class to the route handler and allow that to commit/complete the response because using this approach I can send data from an InputStream,  File, things that are not possible in Spark, Ninja. I prefer to be closer to servlet, to expose the request response nature.
Sure maybe my idea is not sustainable to the end and in this context we must change these concepts. 
For now in my tests I see one big issue with the actual concept: I cannot register a filter for many/all http methods in a single route.
I would love to hear what is your opinion, if you have some issues related to the actual request response cycle (route handler), if you consider that we can improve this concept and to make it more clear. 
I don't want to use a response wrapper (Result for example) because framework X works in this way but if something is better that the actual concept definitely wehave to make some changes.

**Comment by gitblit** [comment]
I'm working on some proposals.  Not sure if I will have them today/tonight.

**Comment by gitblit** [comment]
I re-read through your response.    Thanks for taking the time to explain your position.  I'm ok with the current approach but I will have some Request/Response changes to propose.  I found one or two cases where something I didn't expect to happen did which fails the rule of *least astonishment*.
https://en.wikipedia.org/wiki/Principle_of_least_astonishment

I will not be proposing a result wrapper; I think it is not necessary.

**Comment by gitblit** [comment]
**Filters**

I pushed a massive change to a [branch in my fork](https://github.com/gitblit/pippo/commits/routerOfT).  The purpose of the change is to implement generics on everything that touches `Request`, `Response`, and `Route`.  That turns out to be nearly everything.  :grin:  I'd say it's a proof-of-concept but it took enormous effort and I don't know if I'd have the energy to repeat it again.

The motivation for such a massive change is two-fold: enable creative use of `Route` coupled with creative use of chained `RouteHandler` instances - i.e. filters.

In that branch I demonstrate a solution to your earlier question about metering the `TemplateHandler`.  I'll repeat it here for the purpose of this discussion:

```java
GET("/", new TemplateHandler("index")).meteredAs("pages.root");
```
With  generics we can allow Pippo users to supply their own `Route` implementations that subclass `ro.fortsoft.pippo.core.Route`.  That allows creation build APIs for custom routes perhaps like this:

```java
GET("/api/item/{id}", (req, res, chain) -> {
  // retrieve item here
  chain.next();
}).requiresRole("READ").meteredAs("item.get");

PUT("/api/item{id}", (req, res, chain) -> {
  // update item here
  chain.next();
}).requlresRole("WRITE").meteredAs("item.put");
```

This could then be coupled with something like this:
```java
SecureRouteHandlerChain<T extends Route<Request, Response>> implements RouteHandlerChain {

  Request request;
  Response resopnse;
  Iterator<RouteMatch<MyRoute>> iterator;

  public SecureRouteHandlerChain(Request, Response, List<RouteMatch<MyRoute>> routeMatches) {
    this.request = request;
    this.response = response;
    this.iterator = routeMatches.iterator();
  }

  @Override
  public void next() {
    if (iterator.hasNext()) {
      RouteMatch<MyRoute> routeMatch = iterator.next();
      MyRoute route = routeMatch.getRoute();
      if (route.requiresRole("READ")) {
        if (!request.getSession().canRead()) {
          response.forbidden();
          return;
        }
      } else if (route.requiresRole("WRITE")) {
        if (!request.getSession().canWrite()) {
          response.forbidden();
          return;
        }
      }

      iterator.remove();
      handleRoute(route);
    }
  }
}
```

Another approach to a filter would be to use the router to register `BEFORE` and `AFTER` route handlers and to build a new `RouteHandlerChain` that builds and executes the chain.  This is the approach I am currently taking in my project.

```java
    HandlerChain(Router router, Request request, Response response, List<RouteMatch> routeMatches) {
        this.router = router;
        this.request = request;
        this.response = response;
        this.iterator = buildChain(routeMatches).iterator();
    }

    protected List<RouteMatch> buildChain(List<RouteMatch> routeMatches) {
        String requestUri = Optional.fromNullable(Strings.emptyToNull(request.getContextUri())).or("/");
        List<RouteMatch> all = new ArrayList<>();
        all.addAll(router.findRoutes(requestUri, HttpMethod.BEFORE));
        all.addAll(routeMatches);
        all.addAll(router.findRoutes(requestUri, HttpMethod.AFTER));
        return all;
    }
```

Now of course we don't need generics to accomplish all this, but it looks cleaner to the end-user if we do.

If nothing else comes of this exercise, I did find an important no-no in `Route`:  `Route` **must not be** `Serializable` because it contains a `RouteHandler` and who knows what that is (e.g. lambda, closure ref to a database or something else).

**Comment by decebals** [comment]
I like the idea. 
Related to `Filter`, my idea is to forget about `BEFORE`, `AFTER` and to add only one new in HttpMethod `ALL` and in this mode we preserve the routes order.
I don't know why I marked `Route` with `Serializable`, we can delete this attribute.

**Comment by decebals** [comment]
@gitblit What is your intention related to [generics](https://github.com/gitblit/pippo/commits/routerOfT)?

**Comment by gitblit** [comment]
Not sure.  It adds a great deal of complexity with the massive <>
injections.  Do you think it's worthwhile?

**Comment by decebals** [comment]
It's clear that adding generics we improve the flexibility but it's a price for this and I don't know if it's worthwhile. It's hard to explain a signature as `Application<Q extends Request, R extends Response, T extends Route<Q, R>>` and I don't know if it's a real interest for a custom route (in this stage of development).
I propose to park this idea for the moment. We need to focus on the next release (update documentation, fix bugs, consolidate the API).

**Comment by gitblit** [comment]
Agreed.​
