### ISSUE TITLE
What is our documentation strategy?

### ISSUE THREAD

**Issue by gitblit** [decebals/pippo#85]
Markdown? Asciidoc? Framework for building a static site?

**Comment by decebals** [comment]
It's simple. I have no strategy because it's for the first time when I try this approach with the content on github :) If you have a strategy I would be happy to use it. If not, we will study existing approaches and we choose one of them. I think we need to choose something simple. Ultimately it is important the content.
This part (documentation) is very important for me because a good documentation help a lot on promote.

**Comment by decebals** [comment]
I propose a static site based on Jekyll (Markdown). See [pippo-site](https://github.com/decebals/pippo-site) repository. I am not sure about the best mode to structure the content but I think that for moment it's not a priority. The priority it's to generate the content.
