### ISSUE TITLE
Servlet container sticky points

### ISSUE THREAD

**Issue by gitblit** [decebals/pippo#96]
I've been running Pippo on a couple containers and I have identified some under-the-hood issues.

1. `PippoFilter` is not necessarily loaded on startup of the container I think because it is a Filter instead of a Servlet.  This is an issue because I'd rather see Pippo complete it's initialization on startup rather than on the first request.  We might consider switching `PippoFilter` to be `PippoServlet`.  We don't lose anything AFAICS.
2. `PippoFilter` is called by the container for matching path requests (e.g. `/*`).  That means the response supplied to `PippoFilter` starts off at `200 OK`.  We then set `status(Integer.MAX_VALUE)` to indicate Pippo has not properly processed the response and we require that some handler in the chain to set the status to a valid value.<p />Unfortunately, some containers dislike `status(Integer.MAX_VALUE)` and other containers dislike `status(0)`. <p/>So one of the following needs to happen...
    - We identify an integer value that all containers are happy with: 1?  1000?
    - We set a flag in `Response` to indicate we have a set status (`boolean statusSet = false;`)<br/>**this is my vote**
    - We set a status int in `Response` that is used to set the status int in `HttpServletResponse` at the *end of the request*.

**Comment by decebals** [comment]
> PippoFilter is not necessarily loaded on startup of the container I think because it is a Filter instead of a Servlet. This is an issue because I'd rather see Pippo complete it's initialization on startup rather than on the first request. We might consider switching PippoFilter to be PippoServlet. We don't lose anything AFAICS.

Personal I don't see a problem to initialize the application on the first request. The first request will take some more time. But if you think that a servlet it's teh best solution then I have nothing against in making this transition.
I found a link [1] about `Filter` vs `Servlet` for a web framework.

> - We identify an integer value that all containers are happy with: 1? 1000?
- We set a flag in Response to indicate we have a set status (boolean statusSet = false;)
this is my vote
- We set a status int in Response that is used to set the status int in HttpServletResponse at the end of the request.

I am ok with the solution 2 and 3. Maybe another solution is to set initial status to `NOT_FOUND` instead of `Integer.MAX_VALUE` or `0`.


[1] http://stackoverflow.com/questions/5110077/should-a-web-framework-be-a-filter-or-a-servlet

**Comment by gitblit** [comment]
I pushed the change for the 404 a day or two ago.  Not sure if I am in love with that, but it is a low-cost choice.  Let's see how that goes.

On Servlet vs. Filter.  Maybe instead we should leave the Filter but initialize state in a ContextListener which passes info to the Filter?

**Comment by decebals** [comment]
> On Servlet vs. Filter. Maybe instead we should leave the Filter but initialize state in a ContextListener which passes info to the Filter?

I don't understand your problem. The filters are loaded on application startup (so `PippoFilter.init`->  `Application.init` + `Initializers` are loaded on servlet container startup). The servlets can be loaded on startup or on demand (using `load-on-startup` in `web.xml`).
